package com.example.absolute_cinema_app.retroifit.FilmsRetrofit

data class Film(
    val kinopoiskId: Int,
    val nameRu: String,
    val nameEn: String,
    val nameOriginal: String,
    val posterUrl: String,
    val posterUrlPreview: String,
    val coverUrl: String,
    val logoUrl: String,
    val reviewsCount: Int,
    val ratingKinopoisk: Float,
    val ratingImdb: Float,
    val webUrl: String,
    val year:Int,
    val filmLength:String,
    val slogan: String,
    val description: String,
    val shortDescription: String,
    val editorAnnotation:String,
    val isTicketsAvailable:Boolean,
    val productionStatus: String,
    val type: String,
    val ratingMpaa: String,
    val ratingAgeLimits:String,
    val genres: List<Genre>,
    val startYear:Int,
    val endYear:Int,
    val serial:Boolean,
    val shortFilm:Boolean,
    val completed:Boolean,
)
